### ISSUE TITLE
plotBBox showing 2 legends when using name argument

### ISSUE THREAD

**Issue by makratofil** [rmendels/rerddapXtracto#21]
Hi Roy,

The particular variable I'm plotting (sea surface height (SSH), from pac.ioos.hawaii erddap) is named 'zeta', so I'm trying to rename the legend title to be more descriptive (e.g., SSH (m)). However, whenever I use the 'name' argument within the plotBBox() function or any functions within add_ggplot, the plot ends up having 2 separate legends. Calling "legend.position = "none"" within add_ggplot removes both legends.

Any suggestions for fixing this would be greatly appreciated! Here is the picture of my plot and my code:

![rerddapXtracto_SSH3Dplot_GmTag225](https://user-images.githubusercontent.com/61757397/84327034-32ab7280-ab33-11ea-8c42-9917999239ed.png)

`xpos <- c(-157, -152)`
`ypos <- c(17.5, 21.5)`
`tpos <- c("2019-04-20", "2019-04-20")`
`sshInfo <- rerddap::info('roms_hiig_assim_ssh', url = "https://pae-paha.pacioos.hawaii.edu/erddap/")`
`ssh3D <- rxtracto_3D(sshInfo, parameter = "zeta", xcoord = xpos, ycoord = ypos, tcoord = tpos)`
`dplot <- plotBBox(ssh3D, plotColor = "deep", maxpixels = 100000, name = "SSH (m)")`
`add_ggplot(dplot, 
           theme(axis.text = element_text(colour = "black"),
                 rect = element_rect(size = 2)),
           labs(title = "Sea surface height (zeta, meters)",
                subtitle = "GmTag225: 20 Apr 2018")) %>%
    print(landmask = T)`

**Comment by rmendels** [comment]
@makratofil  Thanks.  I will get back to you.  I believe I have run into this before and figured it out,  but I always forget the solution.  You want the SSH colorbar, not the zeta one,  is that correct.  The other possibility is that there is a bug in the interaction between plotBBox() and plotdap::add_griddap(), which wouldn't surprise me because basically I need to trick 'plotdap' into thinking the extract is from 'rerddap'.  Thanks for the reproducible example,  that makes it easier!

**Comment by rmendels** [comment]
@makratofil I am having issues accessing the dataset,  I have R 4.0 and it doesn't like the cert at that location  (see below).  I assume that is John Maurer,  correct?

```r

sshInfo <- rerddap::info('roms_hiig_assim_ssh', url = "https://pae-paha.pacioos.hawaii.edu/erddap/")
Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) : 
  SSL certificate problem: certificate has expired
```

**Comment by makratofil** [comment]
Thanks! And that's correct: I want the SSH colorbar, not the zeta one (or just rename the title of the zeta one).

**Comment by makratofil** [comment]
Interesting... I also have R 4.0 and haven't run into any issues accessing the dataset. I originally found the server using `rerddap::servers()`, and the link took me to their older website which includes the link to the newer one (the URL in my code) where they've migrated most datasets to. And I believe this would be John Maurer.

**Comment by rmendels** [comment]
@makratofil Okay I was able to reproduce with one of the 'plotDap' examples.  It looks like there were changes in ggplot2() that affect what I need to do to change the name.  So I will have to work on tracking that down,  and getting an update to 'plotdap'.  In the meantime,  you can just fool the program by doing:

```r
names(ssh3D)[1] = 'SSH'
```
and then plot without changing the name.  Haven't gotten it to work with "SSH (m)"  I don't think it likes the parens.  You should  also be able to change the name using add_griddap but I have look up again how to do that.  It has always been a weak feature in ggplot2.

**Comment by rmendels** [comment]
@makratofil  - I believe I have this fixed.  I can't test your specific example right this second because of the Cert problem they restarted their ERDDAP and that dataset is not loaded yet.  But the fixed worked for the example I found.  You can install and test this from this repository:

```r
devtools::install_github("rmendels/rerddapXtracto")

```

Let me know if you are able to install this and if it does the trick.  If you find it works,  I will start going through all the stuff to submit to CRAN.

Thanks for the heads up

**Comment by makratofil** [comment]
@rmendels Great, thanks so much! And good to know why that dataset is not loaded on the server- I went to try your initial fix and got an error that the dataset doesn't exist. 

I was able to install the github version of the package and tested the fix on the marlin tag data- all works well now. Once my particular dataset is back online I'll check and see if it still works, and will let you know if I run into any further issues.

Thanks again!
