### ISSUE TITLE
error using rxtracto_3D:

### ISSUE THREAD

**Issue by abfleishman** [rmendels/rerddapXtracto#7]
library(xtractomatic)# installed version: 3.3.2
library(rerddapXtracto) # installed version: 0.3.3
library(rerddap) # installed version: 0.4.2

```
NCEP<-info( "erdMBchla8day")
erdMBchla8day2011<-rxtracto_3D(dataInfo = NCEP,parameter = "chlorophyll",
                               xcoord = c(135,225),
                               ycoord = c(35,65.5),
                               zcoord = 0.0,
                               zName="altitude",
                               tcoord = c("2010-06-01","2011-06-01"),verbose = T)

```
> Error in rerddap::cache_setup(temp_dir = TRUE) : 
>  unused argument (temp_dir = TRUE)

**Comment by rmendels** [comment]
Hi Abram:

I updated the README a day or two ago because several people have run into this,  I am building against the Github version of rerddap.  Install that from Github,  and the problem should go away.

-Roy

> On Sep 25, 2017, at 9:42 PM, Abram Fleishman <notifications@github.com> wrote:
> 
> library(xtractomatic)# installed version: 3.3.2
> library(rerddapXtracto) # installed version: 0.3.3
> library(rerddap) # installed version: 0.4.2
> 
> NCEP<-info( "erdMBchla8day")
> erdMBchla8day2011<-rxtracto_3D(dataInfo = NCEP,parameter = "chlorophyll",
>                                xcoord = c(135,225),
>                                ycoord = c(35,65.5),
>                                zcoord = 0.0,
>                                zName="altitude",
>                                tcoord = c("2010-06-01","2011-06-01"),verbose = T)
> 
> 
> Error in rerddap::cache_setup(temp_dir = TRUE) :
> unused argument (temp_dir = TRUE)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

**********************
"The contents of this message do not reflect any position of the U.S. Government or NOAA."
**********************
Roy Mendelssohn
Supervisory Operations Research Analyst
NOAA/NMFS
Environmental Research Division
Southwest Fisheries Science Center
***Note new street address***
110 McAllister Way
Santa Cruz, CA 95060
Phone: (831)-420-3666
Fax: (831) 420-3980
e-mail: Roy.Mendelssohn@noaa.gov www: http://www.pfeg.noaa.gov/

"Old age and treachery will overcome youth and skill."
"From those who have been given much, much will be expected" 
"the arc of the moral universe is long, but it bends toward justice" -MLK Jr.
